/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PluginsExploreRouteImport } from './routes/plugins.explore'
import { Route as PluginsInstalledRouteImport } from './routes/plugins.installed'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsExploreRoute = PluginsExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsInstalledRoute = PluginsInstalledRouteImport.update({
  id: '/installed',
  path: '/installed',
  getParentRoute: () => PluginsRoute,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/plugins/explore': typeof PluginsExploreRoute
  '/plugins/installed': typeof PluginsInstalledRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/plugins/explore': typeof PluginsExploreRoute
  '/plugins/installed': typeof PluginsInstalledRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/plugins/explore': typeof PluginsExploreRoute
  '/plugins/installed': typeof PluginsInstalledRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/plugins'
    | '/settings'
    | '/plugins/explore'
    | '/plugins/installed'
    | '/settings/$section'
    | '/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/plugins'
    | '/settings'
    | '/plugins/explore'
    | '/plugins/installed'
    | '/settings/$section'
    | '/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/plugins'
    | '/settings'
    | '/plugins/explore'
    | '/plugins/installed'
    | '/settings/$section'
    | '/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  PluginsRoute: typeof PluginsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/explore': {
      id: '/plugins/explore'
      path: '/explore'
      fullPath: '/plugins/explore'
      preLoaderRoute: typeof PluginsExploreRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/plugins/installed': {
      id: '/plugins/installed'
      path: '/installed'
      fullPath: '/plugins/installed'
      preLoaderRoute: typeof PluginsInstalledRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PluginsRouteChildren {
  PluginsExploreRoute: typeof PluginsExploreRoute
  PluginsInstalledRoute: typeof PluginsInstalledRoute
}

const PluginsRouteChildren: PluginsRouteChildren = {
  PluginsExploreRoute: PluginsExploreRoute,
  PluginsInstalledRoute: PluginsInstalledRoute,
}

const PluginsRouteWithChildren =
  PluginsRoute._addFileChildren(PluginsRouteChildren)

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  PluginsRoute: PluginsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
